apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
spec:
  selector:
    app: quiz-app  # Ensure this matches the label on your pods
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port on the container to route traffic to
  type: LoadBalancer  # Change to NodePort if not using a cloud provider
