apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-frontend
  labels:
    app: streamlit-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-frontend
  template:
    metadata:
      labels:
        app: streamlit-frontend
    spec:
      containers:
      - name: streamlit-frontend
        image: quizcontainer.azurecr.io/streamlit-frontend:latest
        ports:
        - containerPort: 8501
        env:
        - name: STREAMLIT_SERVER_BACKEND_URL
          value: "http://20.235.148.193"  # Backend external IP
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
